### ISSUE TITLE
复现的结果不太好

### ISSUE THREAD

**Issue by shylie728** [DJEddyking/LF2#1]
你好，我想请问一下，我跑了几次您这个代码，都会比您论文里的结果少两个点，想问一下，这是什么原因？您在跑的时候有做什么参数的调整吗?

**Comment by DJEddyking** [comment]
感谢你对我们工作的follow。我们的代码已完全开源，实验过程中没有做额外的处理。关于你的问题，我的建议是：
1、batchsize、epoch等参数是否改变？
2、pretrained过程的参数设置是否改变？
我们以github代码又重新跑了一遍，复现的点数误差在一个点以内。复现的日志和权重文件如下链接：
链接：https://pan.baidu.com/s/14aqzd411GI_CCikDu96_uw 
提取码：LF2M
