### ISSUE TITLE
duke-market复现结果不好

### ISSUE THREAD

**Issue by wangtaos** [DJEddyking/LF2#3]
你好，我想请问一下，我跑了几次您这个代码，duke-market的结果都会比您论文里的结果少两个点，想问一下，这是什么原因？epoch和batchsize都未进行修改。

**Comment by DJEddyking** [comment]
1、以下是我们针对#issue 1的提问重新训练我们的模型得到的权重结果。
链接：https://pan.baidu.com/s/1NRoeJpYBl4KcZYbZXjHoNg 
提取码：LF2M
2、不同源域预训练方式的跨域效果不同。您可以尝试在源域预训练中采用SoftTripletLoss而不是TripletLoss。
