### ISSUE TITLE
Visualize the feature map (heat map)

### ISSUE THREAD

**Issue by TrinhQuocNguyen** [DJEddyking/LF2#5]
Thank you for your wonderful paper and source code. 
I have dug into the code and read the paper carefully, it was a great work.

How did you generate such a heat map?
![image](https://github.com/DJEddyking/LF2/assets/19466163/10ed61bf-c019-42de-9d24-b45550b07311)

Thank you

**Comment by DJEddyking** [comment]
> Thank you for your wonderful paper and source code. I have dug into the code and read the paper carefully, it was a great work.
> 
> How did you generate such a heat map? ![image](https://private-user-images.githubusercontent.com/19466163/296638174-10ed61bf-c019-42de-9d24-b45550b07311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzUzMjIsIm5iZiI6MTcwODg3NTAyMiwicGF0aCI6Ii8xOTQ2NjE2My8yOTY2MzgxNzQtMTBlZDYxYmYtYzAxOS00MmRlLTlkMjQtYjQ1NTUwYjA3MzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE1MzAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYzU2MGZmODcwYzIxOTliNzQ3MTU4YTVmOTcxNzE3NDhjMGY3Zjk5ZWRlYzYxZTQyZWMyY2Y3NTRlNWM0NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XDFqPuJaP9S0acFMYfpzHFFiP8Rg0xsk7pcDtW_o5xU)
> 
> Thank you

Thanks for following our works. We use grad-cam to generate this pictures. Details can be found in [https://arxiv.org/abs/1610.02391](https://arxiv.org/abs/1610.02391)

**Comment by DJEddyking** [comment]
> Thank you for your wonderful paper and source code. I have dug into the code and read the paper carefully, it was a great work.
> 
> How did you generate such a heat map? ![image](https://private-user-images.githubusercontent.com/19466163/296638174-10ed61bf-c019-42de-9d24-b45550b07311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzUzMjIsIm5iZiI6MTcwODg3NTAyMiwicGF0aCI6Ii8xOTQ2NjE2My8yOTY2MzgxNzQtMTBlZDYxYmYtYzAxOS00MmRlLTlkMjQtYjQ1NTUwYjA3MzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE1MzAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYzU2MGZmODcwYzIxOTliNzQ3MTU4YTVmOTcxNzE3NDhjMGY3Zjk5ZWRlYzYxZTQyZWMyY2Y3NTRlNWM0NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XDFqPuJaP9S0acFMYfpzHFFiP8Rg0xsk7pcDtW_o5xU)
> 
> Thank you

Thanks for following our works. We use grad-cam to generate this pictures. Details can be found in [https://arxiv.org/abs/1610.02391](https://arxiv.org/abs/1610.02391)

**Comment by TrinhQuocNguyen** [comment]
Thank you very much.
